[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
